version: '3.9'
services:
  db:
    image: postgres:14.1
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgresql-spina:/var/lib/postgresql/data:delegated
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    depends_on:
      - db

volumes:
  postgresql-spina:
    driver: local

